package com.jinglei.game.server.common;

public enum GAME_GRP_MODE {
	GAME_GRP_MODE_AUTO_LV1,
	GAME_GRP_MODE_AUTO_LV2,
	GAME_GRP_MODE_AUTO_LV3,
	GAME_GRP_MODE_AUTO_LV4,
	GAME_GRP_MODE_CUSTOM,
	GAME_GRP_MODE_MAX,
	GAME_GRP_MODE_AUTO_NUM
}
